import {
  type CellArrayElement,
  Bits,
  type DTValue,
  type DTS,
  type DTO,
  type DTNode,
  type DTProperty,
  type Memreserve,
  is_bits,
  DTCellArray,
  DTMetadata,
  isDTMetadata
} from "./ast.js";

import { TokenStream } from "./TokenStream.js";
import {
  CharToken, CharTokenKind, DirectiveToken,
  DTDirective, RawToken, Token, TokenKind
} from "./tokens.js";
import { Option } from "../option.js";
import { Result } from "../result.js";
import { CoordinatesIn2D, LexerInputStream } from "./LexerInputStream.js";
import { Lexer } from "./Lexer.js";
import { parse as parse_yaml_string } from "yaml";

export const DTS_METADATA_HEADER = `AUTO-GENERATED BY ANALOG ATTACH - DO NOT DELETE OR MODIFY
Required for Analog Attach features. Remove only when devicetree is finalized.` as const;

type Deletable<T> = T & {
  deleted: boolean;
}

type DeletableProperty = Deletable<DTProperty>;
type DeletableNode = Deletable<DTNode<DeletableProperty>>;

export class ParserException extends Error {
  constructor(
    message: string,
    public readonly current_token?: Token,
    public readonly expected_token?: RawToken
  ) {
    const coords = current_token ? ` at ${current_token.row}:${current_token.col}` : "";
    const found = current_token ? ` found ${current_token.kind}${current_token.value ? ` '${current_token.value}'` : ""})` : "";
    const expected = expected_token ? `, expected ${JSON.stringify(expected_token)}` : "";

    super(`${message}${coords}${found}${expected}`);
    this.name = "ParserException";
  }
}

export type ParserError = {
  message: string;
  row?: number;
  col?: number;
}

export type DTSParseResult = {
  dts: DTS;
  metadata: DTMetadata | undefined;
}

export type DTOParseResult = {
  dto: DTO;
  metadata: DTMetadata | undefined;
}

export class Parser {
  constructor(
    private readonly token_stream: TokenStream,
    private readonly trivia_stream: TokenStream,
  ) { }

  public parse_dts(): Result<DTSParseResult, ParserError> {
    try {
      this.consume_directive_token_then_advance(DTDirective.DTSV1);
      this.consume_char_token_then_advance(CharTokenKind.Semicolon);

      const memreserves = this.parse_memreserve_statements();

      const labels = this.parse_labels();
      const root = this.parse_node_statement(labels);

      // Remaining Overlays & Delete Node Directives

      while (!this.token_stream.done) {
        const current = this.token_stream.current;

        // /delete-node/ reference;
        if (current.kind === TokenKind.Directive) {

          this.consume_directive_token_then_advance(DTDirective.DeleteNode);

          const target = this.find_node_by_current_reference(root);
          this.token_stream.advance();

          target.deleted = true;

          this.consume_char_token_then_advance(CharTokenKind.Semicolon);

          continue;
        }

        // Overlay

        const labels = this.parse_labels();

        const target = this.find_node_by_current_reference(root);
        this.token_stream.advance();

        this.parse_and_apply_overlay_statement(labels, target);
      }

      return Result.ok({
        dts: { memreserves, root: strip_node(root) },
        metadata: this.parse_metadata()
      });

    } catch (error) {
      if (error instanceof Error) {
        return Result.error({ message: error.message });
      }
      throw error;
    }
  }

  public parse_dto(): Result<DTOParseResult, ParserError> {
    try {
      this.consume_directive_token_then_advance(DTDirective.DTSV1);
      this.consume_char_token_then_advance(CharTokenKind.Semicolon);

      this.consume_directive_token_then_advance(DTDirective.Plugin);
      this.consume_char_token_then_advance(CharTokenKind.Semicolon);

      const children_map = new Map<string, DeletableNode>();

      const current = this.token_stream.current;
      if (current.kind === TokenKind.Char) {

        // Parsing roots

        while (!this.token_stream.done) {
          this.consume_char_token_then_advance(CharTokenKind.Slash);
          this.consume_char_token_then_advance(CharTokenKind.LBrace);

          // Parsing fragments / new nodes

          while (!this.token_stream.done && this.token_stream.current.kind !== TokenKind.Char) {

            const labels = this.parse_labels();

            const node_identifier_token = this.token_stream.current;
            if (node_identifier_token.kind !== TokenKind.Identifier) {
              throw new ParserException("Expected node/fragment identifier", node_identifier_token);
            }

            if (children_map.has(node_identifier_token.value)) {
              throw new ParserException(
                "Previously defined node with this identifier might conflict",
                node_identifier_token
              );
            }

            const node = this.parse_node_statement(labels);
            children_map.set(node_identifier_token.value, node);
          }

          this.consume_char_token_then_advance(CharTokenKind.RBrace);
          this.consume_char_token_then_advance(CharTokenKind.Semicolon);
        }
      } else {

        // Parsing overlays and transform them to fragments
        let current_number_of_fragments = 0;

        while (!this.token_stream.done) {

          const labels = this.parse_labels();

          const current = this.token_stream.current;

          const target_property = ((): DeletableProperty => {
            if (current.kind === TokenKind.LabelReference) {
              this.token_stream.advance();

              return {
                labels: [],
                name: "target",
                value: [{
                  labels: [],
                  kind: "array",
                  bit_width: Bits.b32,
                  elements: [{
                    labels: [],
                    kind: "label",
                    name: `&${current.value}`
                  }]
                }],
                deleted: false
              };

            } else if (current.kind === TokenKind.PathReference) {
              this.token_stream.advance();

              return {
                labels: [],
                name: "target-path",
                value: [{
                  labels: [],
                  kind: "string",
                  value: current.value
                }],
                deleted: false
              };
            }

            throw new ParserException("Expected reference (path or label)", current);
          })();

          const overlay_properties_map = new Map<string, DeletableProperty>();
          const overlay_children_map = new Map<string, DeletableNode>();

          this.consume_char_token_then_advance(CharTokenKind.LBrace);

          while (!this.token_stream.done && this.token_stream.current.kind !== TokenKind.Char) {

            const labels = this.parse_labels();

            const current = this.token_stream.current;

            // Ignoreing /delete-*/ identifier;

            if (current.kind === TokenKind.Directive) {
              if (current.value === DTDirective.DeleteNode || current.value === DTDirective.DeleteProperty) {
                this.token_stream.advance();
                this.consume_identifier_token_then_advance();
                this.consume_char_token_then_advance(CharTokenKind.Semicolon);
                continue;
              }
              throw new ParserException("Unexpected directive within node", current);
            }

            if (current.kind !== TokenKind.Identifier) {
              throw new ParserException("Looking for identifier that represents property/child name", current);
            }

            const next = Option.unwrap(this.token_stream.lookahead(1));
            if (next.kind !== TokenKind.Char) {
              throw new ParserException("Property/Child name must be followed by '=', '{', or ';'", next);
            }

            // Properties

            if (next.value === CharTokenKind.Equals || next.value === CharTokenKind.Semicolon) {
              if (overlay_children_map.size > 0) {
                throw new ParserException("Properties must be defined before children");
              }

              const property_name = current.value;

              if (overlay_properties_map.has(property_name)) {
                throw new ParserException("Property name will conflict with another previously defined property", current);
              }

              const property = this.parse_property_statement(labels);
              overlay_properties_map.set(property.name, property);
              continue;
            }

            // Children

            if (next.value === CharTokenKind.LBrace) {
              const node_identifier = current.value;

              if (overlay_properties_map.has(node_identifier)) {
                throw new ParserException("Node name will conflict with prefious defined property name", current);
              }

              if (overlay_children_map.has(node_identifier)) {
                throw new ParserException("Node name will conflict with another previously defined node name", current);
              }

              const node = this.parse_node_statement(labels);
              overlay_children_map.set(node_identifier, node);
              continue;
            }

            throw new ParserException("Expected '{','=' or ';' after property/child identifier", next);
          }

          this.consume_char_token_then_advance(CharTokenKind.RBrace);
          this.consume_char_token_then_advance(CharTokenKind.Semicolon);

          children_map.set(`fragment@${current_number_of_fragments}`, {
            labels,
            name: "fragment",
            unit_addr: current_number_of_fragments.toString(),
            properties: [target_property],
            children: [{
              labels: [],
              name: "__overlay__",
              unit_addr: undefined,
              properties: [...overlay_properties_map.values()],
              children: [...overlay_children_map.values()],
              deleted: false
            }],
            deleted: false
          });

          ++current_number_of_fragments;
        }
      }

      return Result.ok({
        dto: {
          root: strip_node({
            labels: [],
            name: "/",
            unit_addr: undefined,
            properties: [],
            children: [...children_map.values()],
            deleted: false
          })
        },
        metadata: this.parse_metadata()
      });

    } catch (error) {
      if (error instanceof Error) {
        return Result.error({ message: error.message });
      }
      throw error;
    }
  }

  private parse_and_apply_overlay_statement(
    labels: Array<string>,
    target_node: DeletableNode
  ) {
    target_node.labels = [...new Set([...labels, ...target_node.labels])];

    this.consume_char_token_then_advance(CharTokenKind.LBrace);

    let defined_at_least_one_child = false;
    while (!this.token_stream.done && this.token_stream.current.kind !== TokenKind.Char) {

      const labels = this.parse_labels();

      const current = this.token_stream.current;

      // Delete Directive
      if (current.kind === TokenKind.Directive) {
        if (current.value === DTDirective.DeleteNode) {
          this.token_stream.advance();
          const identifier_of_node_to_be_deleted = this.consume_identifier_token_then_advance();
          const [name, unit_addr] = split_node_identifier(identifier_of_node_to_be_deleted);
          for (const child of target_node.children) {
            if (child.name === name && child.unit_addr === unit_addr) {
              child.deleted = true;
              break;
            }
          }

          this.consume_char_token_then_advance(CharTokenKind.Semicolon);
          continue;
        }

        if (current.value === DTDirective.DeleteProperty) {
          this.token_stream.advance();
          const name_of_property_to_be_deleted = this.consume_identifier_token_then_advance();
          for (const property of target_node.properties) {
            if (property.name === name_of_property_to_be_deleted) {
              property.deleted = true;
              break;
            }
          }

          this.consume_char_token_then_advance(CharTokenKind.Semicolon);
          continue;
        }

        throw new ParserException("Unexpected directive within overlay", current);
      }

      if (current.kind !== TokenKind.Identifier) {
        throw new ParserException("Expected child/property name identifier", current);
      }

      const next = Option.unwrap(this.token_stream.lookahead(1));
      if (next.kind !== TokenKind.Char) {
        throw new ParserException("Property/Child name must be followed by '=', '{', or ';'", next);
      }

      // Property Override

      if (next.value === CharTokenKind.Equals || next.value === CharTokenKind.Semicolon) {
        if (defined_at_least_one_child) {
          throw new ParserException("Properties must be defined before children");
        }

        const property = this.parse_property_statement(labels);

        const existing_index = target_node.properties
          .findIndex(p => p.name === property.name);

        if (existing_index === -1) {
          target_node.properties.push(property);
        } else {
          target_node.properties[existing_index] = {
            ...property,
            labels: [...new Set([
              ...property.labels,
              ...target_node.properties[existing_index].labels
            ])],
          };
        }

        continue;
      }

      // Child Override

      if (next.value === CharTokenKind.LBrace) {
        defined_at_least_one_child = true;

        const [name, unit_addr] = split_node_identifier(current.value);
        const existing_child = target_node.children.find(c => c.name === name && c.unit_addr === unit_addr);
        if (existing_child) {
          this.token_stream.advance();
          this.parse_and_apply_overlay_statement(labels, existing_child);
        } else {
          const new_child = this.parse_node_statement(labels);
          target_node.children.push(new_child);
        }

        continue;
      }

      throw new ParserException("Expected '{','=' or ';' after property/child identifier", next);
    }

    this.consume_char_token_then_advance(CharTokenKind.RBrace);
    this.consume_char_token_then_advance(CharTokenKind.Semicolon);
  }

  private parse_memreserve_statements(): Array<Memreserve> {
    const memreserves: Array<Memreserve> = [];
    while (!this.token_stream.done
      && this.token_stream.current.kind === TokenKind.Directive
      && this.token_stream.current.value === DTDirective.MemReserve
    ) {

      this.token_stream.advance();

      memreserves.push({
        address: BigInt(this.consume_number_token_then_advance()),
        length: BigInt(this.consume_number_token_then_advance()),
      });

      this.consume_char_token_then_advance(CharTokenKind.Semicolon);
    }
    return memreserves;
  }

  private parse_node_statement(labels: Array<string>): DeletableNode {

    // Node Name & Unit Address

    const [name, unit_addr] = ((): [string, string | undefined] => {
      if (this.token_stream.current.kind === TokenKind.Char
        && this.token_stream.current.value === CharTokenKind.Slash
      ) {
        this.token_stream.advance();
        return ["/", undefined];
      }

      return split_node_identifier(this.consume_identifier_token_then_advance());
    })();

    if (name === "/" && labels.length > 0) {
      throw new ParserException("Root node cannot have labels");
    }

    if (name === "/" && unit_addr !== undefined) {
      throw new ParserException("Root node cannot have a unit address");
    }

    // Node Body Start {

    this.consume_char_token_then_advance(CharTokenKind.LBrace);

    // Node Body Content

    const properties_map = new Map<string, DeletableProperty>();
    const children_map = new Map<string, DeletableNode>();

    while (!this.token_stream.done && this.token_stream.current.kind !== TokenKind.Char) {

      const labels = this.parse_labels();

      const current = this.token_stream.current;

      // Ignoreing /delete-*/ identifier;

      if (current.kind === TokenKind.Directive) {
        if (current.value === DTDirective.DeleteNode || current.value === DTDirective.DeleteProperty) {
          this.token_stream.advance();
          this.consume_identifier_token_then_advance();
          this.consume_char_token_then_advance(CharTokenKind.Semicolon);
          continue;
        }
        throw new ParserException("Unexpected directive within node", current);
      }

      if (current.kind !== TokenKind.Identifier) {
        throw new ParserException("Looking for identifier that represents property/child name", current);
      }

      const next = Option.unwrap(this.token_stream.lookahead(1));
      if (next.kind !== TokenKind.Char) {
        throw new ParserException("Property/Child name must be followed by '=', '{', or ';'", next);
      }

      // Properties

      if (next.value === CharTokenKind.Equals || next.value === CharTokenKind.Semicolon) {
        if (children_map.size > 0) {
          throw new ParserException("Properties must be defined before children");
        }

        const property_name = current.value;

        if (properties_map.has(property_name)) {
          throw new ParserException("Property name will conflict with another previously defined property", current);
        }

        const property = this.parse_property_statement(labels);
        properties_map.set(property.name, property);
        continue;
      }

      // Children

      if (next.value === CharTokenKind.LBrace) {
        const node_identifier = current.value;

        if (properties_map.has(node_identifier)) {
          throw new ParserException("Node name will conflict with prefious defined property name", current);
        }

        if (children_map.has(node_identifier)) {
          throw new ParserException("Node name will conflict with another previously defined node name", current);
        }

        const node = this.parse_node_statement(labels);
        children_map.set(node_identifier, node);
        continue;
      }

      throw new ParserException("Expected '{','=' or ';' after property/child identifier", next);
    }

    // Node Body End };

    this.consume_char_token_then_advance(CharTokenKind.RBrace);
    this.consume_char_token_then_advance(CharTokenKind.Semicolon);

    return {
      labels,
      name,
      unit_addr,
      properties: [...properties_map.values()],
      children: [...children_map.values()],
      deleted: false
    };
  }

  private parse_property_statement(labels: Array<string>): DeletableProperty {

    // Property's name

    const name = this.consume_identifier_token_then_advance();

    // Empty property case (e.g. prop-name;)

    if (this.token_stream.current.kind === TokenKind.Char
      && this.token_stream.current.value === CharTokenKind.Semicolon
    ) {
      this.token_stream.advance();
      return { labels, name, value: { kind: "flag" }, deleted: false };
    }

    // Property with value(s) case
    this.consume_char_token_then_advance(CharTokenKind.Equals);

    const property_value_components = new Array<DTValue>();
    while (!this.token_stream.done && (this.token_stream.current.kind !== TokenKind.Char
      || this.token_stream.current.value !== CharTokenKind.Semicolon)
    ) {

      if (property_value_components.length > 0) {
        this.consume_char_token_then_advance(CharTokenKind.Comma);
      }

      const labels = this.parse_labels();

      const current = this.token_stream.current;

      if (current.kind === TokenKind.String) {
        property_value_components.push({ labels, kind: "string", value: current.value });
        this.token_stream.advance();
        continue;
      }

      if (current.kind === TokenKind.Directive) {
        this.consume_directive_token_then_advance(DTDirective.Bits);

        const bits = Number.parseInt(this.consume_number_token_then_advance());
        if (!is_bits(bits)) {
          throw new ParserException(
            `Invalid bits value: ${bits}. Expected 8, 16, 32 or 64. Got: ${bits}`);
        }

        const cell_array = this.parse_cell_array(labels, bits);
        property_value_components.push(cell_array);
        continue;
      }

      if (current.kind === TokenKind.Char && current.value === CharTokenKind.LAngle) {
        const cell_array = this.parse_cell_array(labels);
        property_value_components.push(cell_array);
        continue;
      }

      if (current.kind === TokenKind.Char && current.value === CharTokenKind.LBracket) {
        const cell_array = this.parse_bytestring(labels);
        property_value_components.push(cell_array);
        continue;
      }

      if (current.kind === TokenKind.LabelReference) {
        property_value_components.push({ labels, kind: "label", name: current.value });
        this.token_stream.advance();
        continue;
      }

      if (current.kind === TokenKind.PathReference) {
        property_value_components.push({ labels, kind: "path", path: current.value });
        this.token_stream.advance();
        continue;
      }

      throw new ParserException("Failed to parse property value. Met unknown token", current);
    }

    this.consume_char_token_then_advance(CharTokenKind.Semicolon);

    return { labels, name, value: property_value_components, deleted: false };
  }

  private consume_identifier_token_then_advance(): string {
    const current = this.token_stream.current;
    if (current.kind !== TokenKind.Identifier) {
      throw new ParserException(
        "Tried to consume identifier, but met other kind of token",
        this.token_stream.current
      );
    }
    this.token_stream.advance();
    return current.value;
  }

  private parse_bytestring(labels: Array<string>): DTCellArray {
    this.consume_char_token_then_advance(CharTokenKind.LBracket);

    const elements = new Array<CellArrayElement>;
    while (!this.token_stream.done && (this.token_stream.current.kind !== TokenKind.Char
      || this.token_stream.current.value !== CharTokenKind.RBracket)
    ) {

      const element_labels = this.parse_labels();

      const current = this.token_stream.current;
      if (current.kind !== TokenKind.Identifier && current.kind !== TokenKind.Number) {
        throw new ParserException("Unexpected token within bytestring", current);
      }

      if (current.value.length % 2 !== 0) {
        throw new ParserException("Bytes can be represented without space, but the number of hex digits must be even", current);
      }

      const bytes = current.value.match(/.{1,2}/g) || [];
      elements.push({ labels: element_labels, kind: "number", value: BigInt("0x" + bytes[0]), repr: "hex" });
      for (let index = 1; index < bytes.length; ++index) {
        elements.push({ labels: [], kind: "number", value: BigInt("0x" + bytes[index]), repr: "hex" });
      }

      this.token_stream.advance();
    }

    this.consume_char_token_then_advance(CharTokenKind.RBracket);

    return { labels, kind: "array", bit_width: Bits.b8, elements };
  }

  private parse_cell_array(labels: Array<string>, bit_width: Bits = Bits.b32): DTCellArray {
    this.consume_char_token_then_advance(CharTokenKind.LAngle);

    const elements = new Array<CellArrayElement>;
    while (!this.token_stream.done && (this.token_stream.current.kind !== TokenKind.Char
      || this.token_stream.current.value !== CharTokenKind.RAngle)
    ) {

      const labels = this.parse_labels();

      const current = this.token_stream.current;

      if (current.kind === TokenKind.LabelReference) {
        elements.push({ labels, kind: "label", name: current.value });
        this.token_stream.advance();
        continue;
      }

      if (current.kind === TokenKind.PathReference) {
        elements.push({ labels, kind: "path", path: current.value });
        this.token_stream.advance();
        continue;
      }

      if (current.kind === TokenKind.Number) {
        elements.push({
          labels, kind: "number", value: BigInt(current.value),
          repr: current.value.startsWith("0x") ? "hex" : "dec"
        });
        this.token_stream.advance();
        continue;
      }

      if (current.kind === TokenKind.Char && current.value === CharTokenKind.LParen) {
        elements.push({ labels, kind: "expression", value: this.parse_expression() });
        continue;
      }

      throw new ParserException("Failed to parse cell array component. Expecting a reference, number or expression", current);
    }

    this.consume_char_token_then_advance(CharTokenKind.RAngle);

    return { labels, kind: "array", bit_width, elements };
  }

  private parse_expression(): string {
    let expression = "";
    let open_parentheses = 0;

    do {
      const current = this.token_stream.current;
      if (current.kind === TokenKind.Char) {
        if (current.value === CharTokenKind.LParen) {
          ++open_parentheses;
        } else if (current.value === CharTokenKind.RParen) {
          --open_parentheses;
        }
      }
      expression += current.value;
      this.token_stream.advance();
    } while (!this.token_stream.done && open_parentheses > 0);

    if (open_parentheses !== 0) {
      throw new ParserException("Expression's open parentheses number doesn't match close ones");
    }

    return expression;
  }

  private parse_labels(): Array<string> {
    const labels = new Array<string>();
    while (!this.token_stream.done && this.token_stream.current.kind === TokenKind.Label) {
      labels.push(this.token_stream.current.value);
      this.token_stream.advance();
    }
    return labels;
  }

  private consume_directive_token_then_advance(directive: DTDirective): DirectiveToken & CoordinatesIn2D {
    const current = this.token_stream.current;
    if (current.kind !== TokenKind.Directive) {
      throw new ParserException(
        "Failed to consume directive token", current,
        { kind: TokenKind.Directive, value: directive }
      );
    }

    if (current.value !== directive) {
      throw new ParserException(
        "Failed to consume specific directive token", current,
        { kind: TokenKind.Directive, value: directive }
      );
    }

    this.token_stream.advance();
    return current;
  }

  private consume_char_token_then_advance(char_kind: CharTokenKind): CharToken & CoordinatesIn2D {
    const current = this.token_stream.current;
    if (current.kind !== TokenKind.Char) {
      throw new ParserException(
        "Failed to consume char token", current,
        { kind: TokenKind.Char, value: char_kind }
      );
    }

    if (current.value !== char_kind) {
      throw new ParserException(
        "Failed to consume specific char token", current,
        { kind: TokenKind.Char, value: char_kind }
      );
    }

    this.token_stream.advance();
    return current;
  }

  private consume_number_token_then_advance(): string {
    const current = this.token_stream.current;
    if (current.kind !== TokenKind.Number) {
      throw new ParserException("Failed to consume number token", current);
    }

    this.token_stream.advance();
    return current.value;
  }

  private find_node_by_current_reference(root: DeletableNode): DeletableNode {
    const current = this.token_stream.current;
    if (current.kind === TokenKind.Char) {
      if (current.value === CharTokenKind.Slash) {
        return root;
      }
      throw new ParserException("Expected / or label/path reference");
    }

    if (current.kind !== TokenKind.LabelReference && current.kind !== TokenKind.PathReference) {
      throw new ParserException("Invalid token, expected label or path reference", current);
    }

    const search_result = current.kind === TokenKind.LabelReference
      ? find_node_by_label(root, current.value)
      : find_node_by_path(root, current.value);

    if (Option.isNone(search_result)) {
      throw new ParserException(`Invalid reference`, current);
    }

    return search_result.value;
  }

  private parse_metadata(): DTMetadata | undefined {
    while (!this.trivia_stream.done) {
      const current = this.trivia_stream.current;
      if (current.kind === TokenKind.CommentBlock && current.value.startsWith(DTS_METADATA_HEADER)) {
        try {
          const metadata = parse_yaml_string(current.value.replace(DTS_METADATA_HEADER, ""));
          return isDTMetadata(metadata) ? metadata : undefined;
        } catch (error) {
          throw new ParserException(`Failed to parse metadata, because: ${error}`);
        }
      }
      this.trivia_stream.advance();
    }
  }
}

// Public utilities

export function parse_dts(raw: string): Result<DTSParseResult, ParserError> {
  const lexer_input_stream = new LexerInputStream(raw);
  const lexer = new Lexer(lexer_input_stream);

  const lexing_result = lexer.lex();
  if (Result.isError(lexing_result)) {
    return Result.error({ message: `Lexing failed with: ${lexing_result.error}` });
  }

  const { tokens, trivia } = lexing_result.value;
  const parser = new Parser(tokens, trivia);

  return parser.parse_dts();
}

export function parse_dto(raw: string): Result<DTOParseResult, ParserError> {
  const lexer_input_stream = new LexerInputStream(raw);
  const lexer = new Lexer(lexer_input_stream);

  const lexing_result = lexer.lex();
  if (Result.isError(lexing_result)) {
    return Result.error({ message: `Lexing failed with: ${lexing_result.error.message}` });
  }

  const { tokens, trivia } = lexing_result.value;
  const parser = new Parser(tokens, trivia);

  return parser.parse_dto();
}

// Private utilities

function find_node_by_label(root: DeletableNode, label: string): Option<DeletableNode> {
  if (root.labels.includes(label)) {
    // eslint-disable-next-line unicorn/no-array-callback-reference
    return Option.some(root);
  }

  return root.children
    .map(child => find_node_by_label(child, label))
    // eslint-disable-next-line unicorn/no-array-callback-reference
    .find(Option.isSome) ?? Option.none();
}

function find_node_by_path(root: DeletableNode, path: string): Option<DeletableNode> {
  if (path.length === 0 || !path.startsWith("/")) {
    throw new ParserException(`Invalid path reference: ${path}`);
  }

  if (path === "/") {
    // eslint-disable-next-line unicorn/no-array-callback-reference
    return Option.some(root);
  }

  const search_result = path
    .split("/")
    .slice(1)
    // eslint-disable-next-line unicorn/no-array-reduce
    .reduce<DeletableNode | undefined>((node, part) => {
      const [name, unit_addr] = split_node_identifier(part);
      return node?.children.find(c => c.name === name && c.unit_addr === unit_addr);
    }, root);

  return search_result
    // eslint-disable-next-line unicorn/no-array-callback-reference
    ? Option.some(search_result)
    : Option.none();
}

function strip_node(node: DeletableNode): DTNode {
  const { deleted, ...rest } = node;
  const a = {
    ...rest,
    properties: node.properties
      .filter(p => !p.deleted)
      .map(p => strip_property(p)),
    children: node.children
      .filter(c => !c.deleted)
      .map(c => strip_node(c)),
  };
  return a;
}

function strip_property({ deleted, ...rest }: DeletableProperty): DTProperty {
  return rest;
};

function split_node_identifier(
  identifier: string
): [string, string | undefined] {
  const [name, unit_addr] = identifier.split("@");
  return [name, unit_addr];
}